apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: ca-cert
    files:
      - tls.cert=rucio_ca.pem
  - name: ruciouser-cert
    files:
      - tls.cert=ruciouser.pem
      - tls.key=ruciouser.key.pem
  - name: hostcert-rucio
    files:
      - tls.cert=hostcert_rucio.pem
      - tls.key=hostcert_rucio.key.pem
      - tls.certkey=hostcert_rucio.certkey.pem
  - name: hostcert-fts
    files:
      - tls.cert=hostcert_fts.pem
      - tls.key=hostcert_fts.key.pem
  - name: hostcert-xrd1
    files:
      - tls.cert=hostcert_xrd1.pem
      - tls.key=hostcert_xrd1.key.pem
  - name: hostcert-xrd2
    files:
      - tls.cert=hostcert_xrd2.pem
      - tls.key=hostcert_xrd2.key.pem
  - name: hostcert-xrd3
    files:
      - tls.cert=hostcert_xrd3.pem
      - tls.key=hostcert_xrd3.key.pem

generatorOptions:
  disableNameSuffixHash: true
